#!/usr/bin/env python
# -*- coding: utf-8 -*-
def get_indices(tarjeta):
	indices = { '/bhdleongoldpremia': '', 
				'/vimencagold': '', 
				'/lopezdeharoclubhemingway': ['lopezdeharo','club hemingway'], 
				'/caribeelite': '', 
				'/scotiabankvisa': '', 
				'/acapvisaclasicalocal': ['acap','clasica'], 
				'/lopezdeharogoldsgym': ['lopezdeharo','golds gym'], 
				'/ademigoldinternacional': ['ademi','gold internacional'], 
				'/ademiclasica': ['ademi','clasica local'], 
				'/ademihipermercadosole': ['ademi','hiperole'], 
				'/alnapgold': ['alnap','gold'], 
				'/apapclasicainternacional': '', 
				'/bancamericaplatinum': '', 
				'/lopezdeharoclasica': ['lopezdeharo','clasica'], 
				'/lopezdeharocasadeespana': ['lopezdeharo','casa de espana'], 
				'/popularmileageplus': ['popular','mileage plus'], 
				'/alnapunionlocal': ['alnap','union local'], 
				'/lopezdeharoclubnaco': ['lopezdeharo','club naco'], 
				'/bhdleonplatinummujer': '', 
				'/bhdleoninfinite': '', 
				'/populargoldinternacional': ['popular','gold internacional'], 
				'/santacruzclasica': '', 
				'/bhdleonclasicapremia': '', 
				'/popularikeafamily': ['popular','ikea family'], 
				'/progresotheplatinumcard': ['progreso','platinum card'], 
				'/bhdleongold': '', 
				'/popularplatinuminternacional': ['popular','platinum internacional'], 
				'/banreservasgoldmultimoneda': '', 
				'/scotiabankpricesmartdiamond': '', 
				'/alnapcompramas': ['alnap','compramas'], 
				'/caribeecard': '', 
				'/bdianthonysclasica': ['bdi','anthonys clasica'], 
				'/apapgold': '', 
				'/popularorbit': ['popular','orbit'], 
				'/federalgold': '', 
				'/vimencagoldpagatodo': '', 
				'/bhdleonblackmujer': '', 
				'/lopezdeharogold': ['lopezdeharo','gold'], 
				'/federalplatinum': '', 
				'/banreservasplatinum': '', 
				'/popularjetblue': ['popular','jetblue'], 
				'/vimencablackgold': '', 
				'/populargoldlocal': ['popular','gold'], 
				'/bhdleonsiremasoro': '', 
				'/banaciempresarial': '', 
				'/acapvisagold': ['acap','gold'], 
				'/banaciblack': '', 
				'/scotiabankaadvantage': '', 
				'/bdiplatinum': ['bdi','platinum'], 
				'/santacruzplatinum': '', 
				'/popularccnplus': ['popular','ccn plus'], 
				'/promericaspiritplatinum': '', 
				'/bdiclasica': ['bdi','clasica'], 
				'/promericaplatinumpremium': '', 
				'/banreservasgold': '', 
				'/popularplatinumlocal': ['popular','platinum'], 
				'/bdianthonysgold': ['bdi','anthonys gold'], 
				'/acapvisaclasicainternacional': ['acap','clasica internacional'], 
				'/promericainfinite': '', 
				'/bdigold': ['bdi','gold'], 
				'/caribeclasicalocal': '', 
				'/banreservasstandard': '', 
				'/bdicrediplan': ['bdi','crediplan'], 
				'/progresolocal': ['progreso','local'], 
				'/scotiabankorange': '', 
				'/banescoinfinite': '', 
				'/promericagold': '', 
				'/bancamericaclasica': '', 
				'/promericamisuper': '', 
				'/apapplatinum': '', 
				'/vimencaplatinum': '', 
				'/santacruzcecomsa': '', 
				'/santacruzinfinite': '', 
				'/banacigold': '', 
				'/alnapconfiamaslocal': ['alnap','confiamas'], 
				'/progresointernacional': ['progreso','internacional'], 
				'/scotiabankgold': '', 
				'/alnapunaselocal': ['alnap','unase local'], 
				'/lopezdeharoplatinum': ['lopezdeharo','platinum'], 
				'/bdianthonysplatinum': ['bdi','anthonys platinum'], 
				'/alnapclasicalocal': ['alnap','clasica local'], 
				'/popularfcbescola': ['popular','fcbescola'], 
				'/scotiabankbravo': '', 
				'/promericaspiritgold': '', 
				'/alnapclasicainternacional': ['alnap','clasica internacional'], 
				'/progresoamericanexpressgold': ['progreso','american express gold'], 
				'/popularclasicainternacional': ['popular','clasica internacional'], 
				'/bdisignature': ['bdi','signature'], 
				'/scotiabankplatinum': '', 
				'/banescogold': '', 
				'/popularprestige': ['popular','prestige'], 
				'/scotiabankaadvantagegold': '', 
				'/ademiempresariallocal': ['ademi','empresarial local'], 
				'/santacruzgold': '', 
				'/bhdleonplatinum': '', 
				'/caribeclasicainternacional': '', 
				'/banreservasmultimoneda': '', 
				'/bdilocal': ['bdi','local'], 
				'/popularcaminantesporlavida': ['popular','caminantes por la vida'], 
				'/bancamericasignature': '', 
				'/caribeplatinum': '', 
				'/caribeoro': '', 
				'/ademiclasicainternacional': ['ademi','clasica internacional'], 
				'/scotiabankmastercard': '', 
				'/bhdleonclasicainternacional': '', 
				'/alnapconfiaentilocal': ['alnap','confia en ti local'], 
				'/apapstandardlocal': '', 
				'/progresoamericanexpresscasadecampoplatinum': ['progreso','casa de campo'], 
				'/bancamericagold': '', 
				'/bhdleonstandardinternacional': '', 
				'/apapstandardinternacional': '', 
				'/banreservasclasica': '', 
				'/banreservasplatinumuniverse': '', 
				'/banescooro': '', 
				'/ademiempresarialinternacional': ['ademi','empresarial internacional'], 
				'/progresogold': ['progreso','gold'], 
				'/banacistandar': '', 
				'/bhdleonclasicalocal': '', 
				'/bhdleongoldmlb': '', 
				'/progresoplatinum': ['progreso','platinum'], 
				'/scotiabankaadvantageplatinum': '', 
				'/alnapunioninternacional': ['alnap','union internacional'], 
				'/progresoamericanexpresssumaccn': ['progreso','suma ccn'], 
				'/apapfamiliar': '', 
				'/banescoclasicainternacional': '', 
				'/ademiempresarialplus': ['ademi','empresarial plus'], 
				'/popularalmacenesiberia': ['popular','almacenes iberia'], 
				'/banacicombustible': '', 
				'/federalclasica': '', 
				'/bhdleonmipais': '', 
				'/apapclasicalocal': '', 
				'/bhdleonstandardlocal': '', 
				'/vimencaclasicainternacional': '', 
				'/banaciplatinum': '', 
				'/popularblacklocal': ['popular','black'], 
				'/vimencaclasicalocal': '', 
				'/banreservasinfinite': '', 
				'/bdisignaturebmcargo': ['bdi','signature bm cargo'], 
				'/promericaplatinum': '', 
				'/popularblackinternacional': ['popular','black internacional'], 
				'/progresoamericanexpress': ['progreso','american express'], 
				'/promericalamaplazos': '', 
				'/bhdleonbeisbolinvernal': '', 
				'/alnapunaseinternacional': ['alnap','unase internacional'], 
				'/banescostandard': '', 
				'/bhdleonlacadena': '', 
				'/banescoplatinum': '', 
				'/popularsegurosuniversal': ['popular','seguros universal'], 
				'/popularmbsignaturecard': ['popular','mb signature'], 
				'/bhdleongoldmujer': '', 
				'/apapgoldinternacional': '', 
				'/scotiabankinfinite': '', 
				'/popularsuperpolasirena': ['popular','sirena'], 
				'/alnapconfiaentiinternacional': ['alnap','confia en ti internacional'], 
				'/popularclasicalocal': ['popular','clasica']
				}

	if indices.get(tarjeta):
		return indices.get(tarjeta)
	else:
		return ['popular','clasica']

def formato_general(title,cont,beneficios):
	contenido = title+'\n'
	for e in cont:
		if cont[e]:
			contenido = contenido+'\n'+e+'|'+cont[e]+','
	if beneficios:
		contenido = contenido+'\n'+'BENEFICIOS:\n'+beneficios+'||'
	#contenido = contenido#.decode('utf-8').replace("\xc1","A").replace("\xe1","a").replace("\xc9","E").replace("\xe9","e").replace("\xcd","I").replace("\xed","i").replace("\xd3","O").replace("\xf3","o").replace("\xda","U").replace("\xfa","u").replace("\xd1","N").replace("\xf1","n")
	return contenido

def limpiar(info):
	return info.encode('utf-8').replace("\xc3\xa1","a").replace("\xc3\xa9","e").replace("\xc3\xad","i").replace("\xc3\xb3","o").replace("\xc3\xba","u").replace("\xc3\x81","A").replace("\xc3\x89","E").replace("\xc3\x8d","I").replace("\xc3\x93","O").replace("\xc3\x9a","U").replace("\xc3\xb1","n").replace("\xc3\x91","N").replace("\xc1","A").replace("\xe1","a").replace("\xc9","E").replace("\xe9","e").replace("\xcd","I").replace("\xed","i").replace("\xd3","O").replace("\xf3","o").replace("\xda","U").replace("\xfa","u").replace("\xd1","N").replace("\xf1","n")